- name: install required packages 1
  snap: name=lxd

    #- name: install required packages 2
    #  apt:
    #    name:
    #    - lxc
    #    - python3-lxc

- name: initialize lxd
  shell:
    cmd: lxd init --minimal
