lxd_project_config:
  config:
    cloud-init.user-data: |
      #cloud-config
      packages:
        - openssh-server
      ssh_pwauth: false
      users:
        - name: ansible
          gecos: Ansible User
          groups: users,admin,wheel
          sudo: ALL=(ALL) NOPASSWD:ALL
          shell: /bin/bash
          ssh_authorized_keys:
            - "{{ ssh_key.public_key }}"
