- hosts: lxc_host
  become: yes
  roles:
  - lxc-host
  tasks:
  - debug: var=lxc_host

- hosts: etcd_cluster
  become: yes
  gather_facts: no
  roles:
  - lxc-container

- hosts: etcd_cluster
  become: yes
  gather_facts: no
  roles:
  - etcd
