- name: create containers
  delegate_to: "{{ lxc_host }}"
  lxd_container:
    name: "{{ inventory_hostname }}"
    source:
      type: image
      mode: pull
      server: https://cloud-images.ubuntu.com/releases/
      protocol: simplestreams
      alias: "24.04"
    profiles: ["default"]
    wait_for_ipv4_addresses: yes
