- name: create a container
  delegate_to: "{{ lxc_host }}"
  lxc_container:
    name: "{{ inventory_hostname }}"
    template: ubuntu-cloud
    template_options: --stream released
    container_log: yes
    container_config:
    - "lxc.network.ipv4 = {{ ansible_host }}/24"
